#cloud-config
hostname: docker-test%
ssh_authorized_keys:
  - ssh-rsa MIIEogIBAAKCAQEArnj/mY5SCsYcLf8m/XRH6of4qKOuJRfvk0cjifgtzettHHEW247M3O/8V0D7WVVzuq3uOJuTJD50gVJIj21e0qaAUrgGR/BtMM3zjy1ih3ihuALYlzAXLd9UEn2mdDGe3oPzi6Ntmp0jp7IyK28HZecyh4ZdADsCy2wvLhjVNMsq/+RnZr31fRX2PVllFTQTw73A0uq2qpu0+U735/DtfDZhDcGx0LDe4nXxZoUFojXZ65oqDHN2vVtMNmKf3i09lGFZRsUA9OeW5aXC0tfliEjlbkHqm07jEYCKG231GhsGNxI+l0nFTjlGjPftYpy4DAxmcWXu9HZaLTi/AcuLGwIBJQKCAQEAhAiKE1bx+lC7YRQdgYhtxj1iOm4HPqpUb3Qa5PMplOmDAMRIpibgOH5Ca4sfEyvo4ExFkp8+6v7UtORSlg2T3a5u8n1siXesk6LGJylDpMn911wZhytPz6/smF8WLmq9ah6qd4KYIfpgK+DMBTFtYd9kgjwqtBD7MihbDiChWGEhQ80MeIfbS5STwClTT2PK1vZBpHYX8nEQW0uUrBcEEKgrjP+utBjP8h5n6AbcP2RchVFaV6roJB6HoMgdTBb5VqESav8DonDtZK9Tfj+DXDC1ilHyANmiQ2ZaJCJ9/7+ye5kxq8gO0wu1RoIYrcj29nAY4jLDWyWPbc2GSIrQrQKBgQD6VoEHrQyMV8JevcE3CUDZgzMryqV08haNp4Ih7QTO8h7p36loRxnbrBGWnYNzWjyIlsvxhpw+Yw1HFEnl7B/nzaaNoYrlJh/njuOweiDqVlXSeLn4+CM6XMwWphq0NrI8hq2JAMvfb2e/i9tKKePVJD2OnK0fH3q+JuvIqgjnYQKBgQCyazj89dlQgXPUQaq20MGlEjLi3Kk0XLjj/bs/PBbZKvAZDzQirePwbU52DUGmGMb7pKK3/7VhBgEbDaKTOzgelEFhBY2ybvuaNkga35npCmmQx+TNRp5bbe0zM0o+9gbm+sf9GBD22jjpv15wUxPltHGSYKyW02VnousXLsIP+wKBgC9ceUakMs5xd8y8HaKg4sFeAsMYgCrhsT1k4USwTQSOq+cOo4JuUQALy/nmctCiXnq0vszURxK4yykfg5ozl1VeQhrLiPrriX7V2Ayhe9lOmp1wyTzwrLgDt+ib9zbZ6l56WC6tH6bP4zITilojmc5gzWArerLccSrkxNLvvH7NAoGBAJ8hXFc8Iq+WDVxx60kbDZM5vq6pIUpgiToL0ISBs4NrfDIGpB7uHlL5tK56hqjlqo1pUtt1XJTOAPxz8d1Cp6ySEMwnjDdcENWmCPVfpPJxEguB2eeELF9iCuh52m+Be8cXBWUxI+MVqGHGWyXpO0J+V3S3FniutGNZ9EUb3YPfAoGAdbfPzRYF1QAAecU+8SkEy/bLrNZxlvupqY7HrwZkA8xSIF7Lfz0qVE/yP1FoAAOBCMadTE1hudRZDI61/59w2fD/E+tQhW0lsq376FW8ujow8piOtKAV/yEh93zeC0uRDA8Mr0+DFyXR+z4NDdU2RTJ5nFGWBUS2NSE61sPQBEE=
  
runcmd:
  - echo "true" > /home/rancher/provisioned

rancher:
  network:
    dns:
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
      override: true # Override DHCP assigned nameservers
    interfaces:
      eth0:
        dhcp: true
      eth1:
        dhcp: false
        address: 172.68.1.100/24
        gateway: 172.68.1.1
        mtu: 1500
        vlans: 100
