#cloud-config
hostname: docker-test%
ssh_authorized_keys:
  - ssh-rsa MIIEogIBAAKCAQEArnj/mY5SCsYcLf8m/XRH6of4qKOuJRfvk0cjifgtzettHHEW
247M3O/8V0D7WVVzuq3uOJuTJD50gVJIj21e0qaAUrgGR/BtMM3zjy1ih3ihuALY
lzAXLd9UEn2mdDGe3oPzi6Ntmp0jp7IyK28HZecyh4ZdADsCy2wvLhjVNMsq/+Rn
Zr31fRX2PVllFTQTw73A0uq2qpu0+U735/DtfDZhDcGx0LDe4nXxZoUFojXZ65oq
DHN2vVtMNmKf3i09lGFZRsUA9OeW5aXC0tfliEjlbkHqm07jEYCKG231GhsGNxI+
l0nFTjlGjPftYpy4DAxmcWXu9HZaLTi/AcuLGwIBJQKCAQEAhAiKE1bx+lC7YRQd
gYhtxj1iOm4HPqpUb3Qa5PMplOmDAMRIpibgOH5Ca4sfEyvo4ExFkp8+6v7UtORS
lg2T3a5u8n1siXesk6LGJylDpMn911wZhytPz6/smF8WLmq9ah6qd4KYIfpgK+DM
BTFtYd9kgjwqtBD7MihbDiChWGEhQ80MeIfbS5STwClTT2PK1vZBpHYX8nEQW0uU
rBcEEKgrjP+utBjP8h5n6AbcP2RchVFaV6roJB6HoMgdTBb5VqESav8DonDtZK9T
fj+DXDC1ilHyANmiQ2ZaJCJ9/7+ye5kxq8gO0wu1RoIYrcj29nAY4jLDWyWPbc2G
SIrQrQKBgQD6VoEHrQyMV8JevcE3CUDZgzMryqV08haNp4Ih7QTO8h7p36loRxnb
rBGWnYNzWjyIlsvxhpw+Yw1HFEnl7B/nzaaNoYrlJh/njuOweiDqVlXSeLn4+CM6
XMwWphq0NrI8hq2JAMvfb2e/i9tKKePVJD2OnK0fH3q+JuvIqgjnYQKBgQCyazj8
9dlQgXPUQaq20MGlEjLi3Kk0XLjj/bs/PBbZKvAZDzQirePwbU52DUGmGMb7pKK3
/7VhBgEbDaKTOzgelEFhBY2ybvuaNkga35npCmmQx+TNRp5bbe0zM0o+9gbm+sf9
GBD22jjpv15wUxPltHGSYKyW02VnousXLsIP+wKBgC9ceUakMs5xd8y8HaKg4sFe
AsMYgCrhsT1k4USwTQSOq+cOo4JuUQALy/nmctCiXnq0vszURxK4yykfg5ozl1Ve
QhrLiPrriX7V2Ayhe9lOmp1wyTzwrLgDt+ib9zbZ6l56WC6tH6bP4zITilojmc5g
zWArerLccSrkxNLvvH7NAoGBAJ8hXFc8Iq+WDVxx60kbDZM5vq6pIUpgiToL0ISB
s4NrfDIGpB7uHlL5tK56hqjlqo1pUtt1XJTOAPxz8d1Cp6ySEMwnjDdcENWmCPVf
pPJxEguB2eeELF9iCuh52m+Be8cXBWUxI+MVqGHGWyXpO0J+V3S3FniutGNZ9EUb
3YPfAoGAdbfPzRYF1QAAecU+8SkEy/bLrNZxlvupqY7HrwZkA8xSIF7Lfz0qVE/y
P1FoAAOBCMadTE1hudRZDI61/59w2fD/E+tQhW0lsq376FW8ujow8piOtKAV/yEh
93zeC0uRDA8Mr0+DFyXR+z4NDdU2RTJ5nFGWBUS2NSE61sPQBEE=
  
runcmd:
  - echo "true" > /home/rancher/provisioned

rancher:
  network:
    dns:
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
      override: true # Override DHCP assigned nameservers
    interfaces:
      eth0:
        dhcp: true
      eth1:
        dhcp: false
        address: 172.68.1.100/24
        gateway: 172.68.1.1
        mtu: 1500
        vlans: 100
