#cloud-config
hostname: docker-test%
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEArnj/mY5SCsYcLf8m/XRH6of4qKOuJRfvk0cjifgtzettHHEW247M3O/8V0D7WVVzuq3uOJuTJD50gVJIj21e0qaAUrgGR/BtMM3zjy1ih3ihuALYlzAXLd9UEn2mdDGe3oPzi6Ntmp0jp7IyK28HZecyh4ZdADsCy2wvLhjVNMsq/+RnZr31fRX2PVllFTQTw73A0uq2qpu0+U735/DtfDZhDcGx0LDe4nXxZoUFojXZ65oqDHN2vVtMNmKf3i09lGFZRsUA9OeW5aXC0tfliEjlbkHqm07jEYCKG231GhsGNxI+l0nFTjlGjPftYpy4DAxmcWXu9HZaLTi/AcuLGw
  
runcmd:
  - echo "true" > /home/rancher/provisioned

rancher:
  network:
    dns:
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
      override: true # Override DHCP assigned nameservers
    interfaces:
      eth0:
        dhcp: true
      eth1:
        dhcp: false
        address: 172.68.1.100/24
        gateway: 172.68.1.1
        mtu: 1500
        vlans: 100
